# Generated by Django 5.1.7 on 2026-06-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('service', models.CharField(choices=[('Bridal Consultation', 'Bridal Consultation'), ('Punjabi Suit Design', 'Punjabi Suit Design'), ('Party Wear Styling', 'Party Wear Styling'), ('Custom Tailoring', 'Custom Tailoring'), ('Measurement Appointment', 'Measurement Appointment')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
