# Generated by Django 5.1.7 on 2026-06-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_review_alter_appointment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
