# Generated by Django 5.1.7 on 2026-09-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0004_alter_review_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(blank=True, choices=[('Bridal Consultation', 'Bridal Consultation'), ('Punjabi Suit Design', 'Punjabi Suit Design'), ('Party Wear Styling', 'Party Wear Styling'), ('Custom Tailoring', 'Custom Tailoring'), ('Measurement Appointment', 'Measurement Appointment')], default='Consultation', max_length=50),
        ),
    ]
